const express = require('express');
const auth = require('../middleware/authMiddleware');
const controller = require('../controllers/fileSpaceController');
const syncController = require('../controllers/fileSpaceSyncController');

const router = express.Router();
router.get('/filespace/media/:fileId', controller.media);
router.use('/filespace', auth);
router.get('/filespace/root', controller.root);
router.get('/filespace/search', controller.search);
router.get('/filespace/trash', controller.trash);
router.get('/filespace/audit', controller.auditLog);
router.get('/filespace/sync/snapshot', syncController.snapshot);
router.get('/filespace/sync/changes', syncController.changes);
router.get('/filespace/destinations', controller.destinations);
router.post('/filespace/move', controller.move);
router.delete('/filespace/trash/files', controller.purgeTrashFiles);
router.post('/filespace/trash/:type/:id/restore', controller.restoreTrash);
router.delete('/filespace/trash/:type/:id', controller.purgeTrash);
router.get('/filespace/folders/:folderId', controller.list);
router.get('/filespace/folders/:folderId/access', controller.getFolderAccess);
router.put('/filespace/folders/:folderId/access', controller.updateFolderAccess);
router.patch('/filespace/folders/:folderId', controller.renameFolder);
router.delete('/filespace/folders/:folderId', controller.removeFolder);
router.post('/filespace/folders', controller.createFolder);
router.post('/filespace/uploads', controller.startUpload);
router.put('/filespace/uploads/:fileId/content', controller.uploadContent);
router.post('/filespace/uploads/:fileId/complete', controller.completeUpload);
router.delete('/filespace/files', controller.removeMany);
router.get('/filespace/files/:fileId/download', controller.download);
router.get('/filespace/files/:fileId/content', controller.downloadContent);
router.get('/filespace/files/:fileId/open', controller.open);
router.get('/filespace/files/:fileId/preview', controller.preview);
router.get('/filespace/files/:fileId/versions', controller.fileVersions);
router.post('/filespace/files/:fileId/versions/initiate', controller.startVersionUpload);
router.put('/filespace/files/:fileId/versions/:versionId/content', controller.uploadVersionContent);
router.post('/filespace/files/:fileId/versions/:versionId/complete', controller.completeVersionUpload);
router.get('/filespace/files/:fileId/versions/:versionId/download', controller.downloadVersion);
router.get('/filespace/files/:fileId/versions/:versionId/open', controller.openVersion);
router.post('/filespace/files/:fileId/versions/:versionId/restore', controller.restoreVersion);
router.post('/filespace/files/:fileId/send-to-chat', controller.sendToChat);
router.post('/filespace/files/:fileId/rescan', controller.rescan);
router.patch('/filespace/files/:fileId', controller.renameFile);
router.delete('/filespace/files/:fileId', controller.remove);

module.exports = router;
